using System;


namespace ERP.API.Models
{
    public class Delivery
    {
        /// <summary>
        /// Auto-generated primary key (omit in POST)
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// User who created the delivery (required in POST)
        /// </summary>
        public int? UserCreated { get; set; }

        /// <summary>
        /// Auto-generated by DB (omit in POST)
        /// </summary>
        public DateTime? DateCreated { get; set; }

        /// <summary>
        /// User who last updated the delivery (optional)
        /// </summary>
        public int? UserUpdated { get; set; }

        /// <summary>
        /// Date of last update (auto-generated by DB, omit in POST)
        /// </summary>
        public DateTime? DateUpdated { get; set; }

        /// <summary>
        /// Sales order ID (optional in POST)
        /// </summary>
        public string? SalesOrderId { get; set; }

        /// <summary>
        /// Purchase order ID (optional in POST)
        /// </summary>
        public string? PoId { get; set; }

        /// <summary>
        /// Auto-generated unique delivery identifier (omit in POST)
        /// </summary>
        public string? DeliveryId { get; set; }

        /// <summary>
        /// Delivery date (required in POST)
        /// </summary>
        public DateTime DeliveryDate { get; set; }

        /// <summary>
        /// Delivery status (default 'Pending', required in POST)
        /// </summary>
        public string? DeliveryStatus { get; set; }

        /// <summary>
        /// Dispatch address (optional)
        /// </summary>
        public string? DispatchAddress { get; set; }
        public string? Priority { get; set; }
        public string? TransporterName { get; set; }
        public string? VehicleNo { get; set; }
        public string? DriverName { get; set; }
        public long? DriverContact { get; set; }
        public string? ModeOfDelivery { get; set; }
        public string? InvoiceId { get; set; }
        public List<SalesItemResponse>? Items { get; set; }
        public int? TotalRecords { get; set; }
    }
}
