-- ========================================================
-- SYNC SCRIPT: Issues Management Schema (Full Sync)
-- This script adds missing columns to 'issues' and 'issue_items'
-- ========================================================

-- 1. Update 'issues' table
ALTER TABLE issues ADD COLUMN IF NOT EXISTS user_created INTEGER;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS date_created TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS user_updated INTEGER;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS date_updated TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS location_id VARCHAR(50);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS bom_id TEXT[];
ALTER TABLE issues ADD COLUMN IF NOT EXISTS iss_to VARCHAR(100);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS issue_to VARCHAR(255);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS customer_name VARCHAR(255);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS party_branch VARCHAR(255);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS status VARCHAR(50);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS sales_representative VARCHAR(100);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS goods_consign_from VARCHAR(255);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS goods_consign_to VARCHAR(255);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS delivered_by VARCHAR(255);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS booking_address TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS booking_qty INTEGER;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS app_value NUMERIC(18,2);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS received_on TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS bom_name VARCHAR(255);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS demo_from VARCHAR(100);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS demo_report VARCHAR(255);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS demo_request VARCHAR(255);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS demo_remarks TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS doc_id VARCHAR(50);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS issue_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS ref_no VARCHAR(100);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS ref_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS comments TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS narration TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS receipt_id VARCHAR(100);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS generate_invoice VARCHAR(10);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS bill_no VARCHAR(100);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS bill_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS doctor_name VARCHAR(255);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS billing_description TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS billing_amount NUMERIC(18,2);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS gross NUMERIC(18,2);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS total_qty NUMERIC(18,4);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS amount_in_words TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS eway_bill_no VARCHAR(100);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS eway_bill_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS transporter VARCHAR(255);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS vehicle_no VARCHAR(50);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS from_gstin VARCHAR(20);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS to_gstin VARCHAR(20);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS distance INTEGER;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS transporter_id VARCHAR(50);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS eway_bill_status VARCHAR(50);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS supply_type VARCHAR(5);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS sub_type VARCHAR(5);
ALTER TABLE issues ADD COLUMN IF NOT EXISTS doc_type VARCHAR(10);

-- 2. Update 'issue_items' table
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS s_no INTEGER;
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS make VARCHAR(100);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS product VARCHAR(255);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS model VARCHAR(100);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS item VARCHAR(255);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS equ_ins VARCHAR(255);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS batch_no VARCHAR(100);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS receipt_no VARCHAR(100);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS unit VARCHAR(50);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS qty_avl NUMERIC(18,4);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS qty NUMERIC(18,4);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS rate NUMERIC(18,4);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS amount NUMERIC(18,4);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS remarks TEXT;
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS hsn_code VARCHAR(20);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS cgst_rate NUMERIC(18,4);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS sgst_rate NUMERIC(18,4);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS igst_rate NUMERIC(18,4);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS cgst_amount NUMERIC(18,4);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS sgst_amount NUMERIC(18,4);
ALTER TABLE issue_items ADD COLUMN IF NOT EXISTS igst_amount NUMERIC(18,4);

-- 3. Update 'issue_optional_items' table
ALTER TABLE issue_optional_items ADD COLUMN IF NOT EXISTS s_no INTEGER;
ALTER TABLE issue_optional_items ADD COLUMN IF NOT EXISTS opt_make VARCHAR(100);
ALTER TABLE issue_optional_items ADD COLUMN IF NOT EXISTS opt_category VARCHAR(100);
ALTER TABLE issue_optional_items ADD COLUMN IF NOT EXISTS opt_product VARCHAR(255);
ALTER TABLE issue_optional_items ADD COLUMN IF NOT EXISTS opt_model VARCHAR(100);
ALTER TABLE issue_optional_items ADD COLUMN IF NOT EXISTS opt_item VARCHAR(255);
ALTER TABLE issue_optional_items ADD COLUMN IF NOT EXISTS opt_item_desc TEXT;
ALTER TABLE issue_optional_items ADD COLUMN IF NOT EXISTS opt_qty NUMERIC(18,4);
ALTER TABLE issue_optional_items ADD COLUMN IF NOT EXISTS opt_rate NUMERIC(18,4);
ALTER TABLE issue_optional_items ADD COLUMN IF NOT EXISTS opt_amount NUMERIC(18,4);
