CREATE TABLE public.item_master (
    id SERIAL PRIMARY KEY,
    user_created INT REFERENCES public.users(userid),
    date_created TIMESTAMP DEFAULT now(),
    user_updated INT REFERENCES public.users(userid),
    date_updated TIMESTAMP,
    group_id INT REFERENCES public.inventory_group(id),
    category_id INT REFERENCES public.categories(id),
    inventory_method_id INT REFERENCES public.inventory_method(id),
    uom_id INT REFERENCES public.uom(id),
    valuation_method_id INT REFERENCES public.valuation_method(id),
    item_name VARCHAR(255),
   long_item_name VARCHAR(500),
    item_code VARCHAR(255) UNIQUE,
    item_description varchar(255),
    make_id int references make(id),
    model_id int references model(id),
    product_id int references product(id),
    brand VARCHAR(255),
    inventory_type VARCHAR(100),
    specification VARCHAR(255),
    criticality VARCHAR(10),
    stock_to_bank VARCHAR(100),
    lp_rate DECIMAL(12,2),
    unit_price NUMERIC(12,2),
    tax_percentage NUMERIC(5,2),
    valuation_method VARCHAR(100),
    related_stock_account VARCHAR(100),
    cf INT,
    hsn VARCHAR(20),
    bom_applicable BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    image_url VARCHAR(255),
    cat_no varchar(255)
   
);